version: '3.7'

services:
  app:
    image: ruby:3.2
    container_name: app
    volumes:
      - ../app:/app
    ports:
      - '3000:3000'
    tty: true
    working_dir: /app

  database:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: database
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports: # 他のコンテナからmysqlクライアントを用いてアクセスしたい場合は、portを公開する必要あり
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf # configファイル
      - data-volume:/var/lib/mysql # DBデータの保存領域
      - ../sql:/usr/scripts # 実行したいSQLを保管しておく場所

volumes:
  data-volume:
