version: '3.7'

services:
  app:
    image: ruby:3.2
    container_name: ruby
    volumes:
      - ../app:/app
    ports:
      - 3000:3000
    tty: true
    working_dir: /app
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
      - data-volume:/var/lib/mysql
      - ../sql:/usr/scripts

volumes:
  data-volume:
